// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/file/repo.proto

package file

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RepoService_ListRepos_FullMethodName  = "/api.file.RepoService/ListRepos"
	RepoService_CreateRepo_FullMethodName = "/api.file.RepoService/CreateRepo"
	RepoService_UpdateRepo_FullMethodName = "/api.file.RepoService/UpdateRepo"
	RepoService_DeleteRepo_FullMethodName = "/api.file.RepoService/DeleteRepo"
	RepoService_TestRepo_FullMethodName   = "/api.file.RepoService/TestRepo"
)

// RepoServiceClient is the client API for RepoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepoServiceClient interface {
	ListRepos(ctx context.Context, in *Repo_ListRequest, opts ...grpc.CallOption) (*Repo_ListResponse, error)
	CreateRepo(ctx context.Context, in *Repo_CreateRequest, opts ...grpc.CallOption) (*Repo_CreateResponse, error)
	UpdateRepo(ctx context.Context, in *Repo_UpdateRequest, opts ...grpc.CallOption) (*Repo_UpdateResponse, error)
	DeleteRepo(ctx context.Context, in *Repo_DeleteRequest, opts ...grpc.CallOption) (*Repo_DeleteResponse, error)
	TestRepo(ctx context.Context, in *Repo_TestRequest, opts ...grpc.CallOption) (*Repo_TestResponse, error)
}

type repoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepoServiceClient(cc grpc.ClientConnInterface) RepoServiceClient {
	return &repoServiceClient{cc}
}

func (c *repoServiceClient) ListRepos(ctx context.Context, in *Repo_ListRequest, opts ...grpc.CallOption) (*Repo_ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repo_ListResponse)
	err := c.cc.Invoke(ctx, RepoService_ListRepos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoServiceClient) CreateRepo(ctx context.Context, in *Repo_CreateRequest, opts ...grpc.CallOption) (*Repo_CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repo_CreateResponse)
	err := c.cc.Invoke(ctx, RepoService_CreateRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoServiceClient) UpdateRepo(ctx context.Context, in *Repo_UpdateRequest, opts ...grpc.CallOption) (*Repo_UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repo_UpdateResponse)
	err := c.cc.Invoke(ctx, RepoService_UpdateRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoServiceClient) DeleteRepo(ctx context.Context, in *Repo_DeleteRequest, opts ...grpc.CallOption) (*Repo_DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repo_DeleteResponse)
	err := c.cc.Invoke(ctx, RepoService_DeleteRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoServiceClient) TestRepo(ctx context.Context, in *Repo_TestRequest, opts ...grpc.CallOption) (*Repo_TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repo_TestResponse)
	err := c.cc.Invoke(ctx, RepoService_TestRepo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepoServiceServer is the server API for RepoService service.
// All implementations must embed UnimplementedRepoServiceServer
// for forward compatibility.
type RepoServiceServer interface {
	ListRepos(context.Context, *Repo_ListRequest) (*Repo_ListResponse, error)
	CreateRepo(context.Context, *Repo_CreateRequest) (*Repo_CreateResponse, error)
	UpdateRepo(context.Context, *Repo_UpdateRequest) (*Repo_UpdateResponse, error)
	DeleteRepo(context.Context, *Repo_DeleteRequest) (*Repo_DeleteResponse, error)
	TestRepo(context.Context, *Repo_TestRequest) (*Repo_TestResponse, error)
	mustEmbedUnimplementedRepoServiceServer()
}

// UnimplementedRepoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepoServiceServer struct{}

func (UnimplementedRepoServiceServer) ListRepos(context.Context, *Repo_ListRequest) (*Repo_ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRepos not implemented")
}
func (UnimplementedRepoServiceServer) CreateRepo(context.Context, *Repo_CreateRequest) (*Repo_CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRepo not implemented")
}
func (UnimplementedRepoServiceServer) UpdateRepo(context.Context, *Repo_UpdateRequest) (*Repo_UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRepo not implemented")
}
func (UnimplementedRepoServiceServer) DeleteRepo(context.Context, *Repo_DeleteRequest) (*Repo_DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRepo not implemented")
}
func (UnimplementedRepoServiceServer) TestRepo(context.Context, *Repo_TestRequest) (*Repo_TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestRepo not implemented")
}
func (UnimplementedRepoServiceServer) mustEmbedUnimplementedRepoServiceServer() {}
func (UnimplementedRepoServiceServer) testEmbeddedByValue()                     {}

// UnsafeRepoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepoServiceServer will
// result in compilation errors.
type UnsafeRepoServiceServer interface {
	mustEmbedUnimplementedRepoServiceServer()
}

func RegisterRepoServiceServer(s grpc.ServiceRegistrar, srv RepoServiceServer) {
	// If the following call pancis, it indicates UnimplementedRepoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RepoService_ServiceDesc, srv)
}

func _RepoService_ListRepos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Repo_ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServiceServer).ListRepos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoService_ListRepos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServiceServer).ListRepos(ctx, req.(*Repo_ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoService_CreateRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Repo_CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServiceServer).CreateRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoService_CreateRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServiceServer).CreateRepo(ctx, req.(*Repo_CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoService_UpdateRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Repo_UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServiceServer).UpdateRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoService_UpdateRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServiceServer).UpdateRepo(ctx, req.(*Repo_UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoService_DeleteRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Repo_DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServiceServer).DeleteRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoService_DeleteRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServiceServer).DeleteRepo(ctx, req.(*Repo_DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepoService_TestRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Repo_TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServiceServer).TestRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepoService_TestRepo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServiceServer).TestRepo(ctx, req.(*Repo_TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepoService_ServiceDesc is the grpc.ServiceDesc for RepoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.file.RepoService",
	HandlerType: (*RepoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRepos",
			Handler:    _RepoService_ListRepos_Handler,
		},
		{
			MethodName: "CreateRepo",
			Handler:    _RepoService_CreateRepo_Handler,
		},
		{
			MethodName: "UpdateRepo",
			Handler:    _RepoService_UpdateRepo_Handler,
		},
		{
			MethodName: "DeleteRepo",
			Handler:    _RepoService_DeleteRepo_Handler,
		},
		{
			MethodName: "TestRepo",
			Handler:    _RepoService_TestRepo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/file/repo.proto",
}
