// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/base/setting.proto

package base

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Setting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: gorm:"primary_key;auto_increment"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key;auto_increment"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"size:128;not null;unique"
	Key           string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty" gorm:"size:128;not null;unique"`
	Value         string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting) Reset() {
	*x = Setting{}
	mi := &file_api_base_setting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_setting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_api_base_setting_proto_rawDescGZIP(), []int{0}
}

func (x *Setting) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Setting) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Setting) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Setting) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Setting) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Setting_GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting_GetRequest) Reset() {
	*x = Setting_GetRequest{}
	mi := &file_api_base_setting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting_GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting_GetRequest) ProtoMessage() {}

func (x *Setting_GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_setting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting_GetRequest.ProtoReflect.Descriptor instead.
func (*Setting_GetRequest) Descriptor() ([]byte, []int) {
	return file_api_base_setting_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Setting_GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Setting_GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Setting               `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting_GetResponse) Reset() {
	*x = Setting_GetResponse{}
	mi := &file_api_base_setting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting_GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting_GetResponse) ProtoMessage() {}

func (x *Setting_GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_setting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting_GetResponse.ProtoReflect.Descriptor instead.
func (*Setting_GetResponse) Descriptor() ([]byte, []int) {
	return file_api_base_setting_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Setting_GetResponse) GetResult() *Setting {
	if x != nil {
		return x.Result
	}
	return nil
}

type Setting_UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting_UpdateRequest) Reset() {
	*x = Setting_UpdateRequest{}
	mi := &file_api_base_setting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting_UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting_UpdateRequest) ProtoMessage() {}

func (x *Setting_UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_setting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting_UpdateRequest.ProtoReflect.Descriptor instead.
func (*Setting_UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_base_setting_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Setting_UpdateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Setting_UpdateRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Setting_UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Setting               `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting_UpdateResponse) Reset() {
	*x = Setting_UpdateResponse{}
	mi := &file_api_base_setting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting_UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting_UpdateResponse) ProtoMessage() {}

func (x *Setting_UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_setting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting_UpdateResponse.ProtoReflect.Descriptor instead.
func (*Setting_UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_base_setting_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Setting_UpdateResponse) GetResult() *Setting {
	if x != nil {
		return x.Result
	}
	return nil
}

type Setting_ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting_ResetRequest) Reset() {
	*x = Setting_ResetRequest{}
	mi := &file_api_base_setting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting_ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting_ResetRequest) ProtoMessage() {}

func (x *Setting_ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_setting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting_ResetRequest.ProtoReflect.Descriptor instead.
func (*Setting_ResetRequest) Descriptor() ([]byte, []int) {
	return file_api_base_setting_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Setting_ResetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Setting_ResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting_ResetResponse) Reset() {
	*x = Setting_ResetResponse{}
	mi := &file_api_base_setting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting_ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting_ResetResponse) ProtoMessage() {}

func (x *Setting_ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_setting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting_ResetResponse.ProtoReflect.Descriptor instead.
func (*Setting_ResetResponse) Descriptor() ([]byte, []int) {
	return file_api_base_setting_proto_rawDescGZIP(), []int{0, 5}
}

var File_api_base_setting_proto protoreflect.FileDescriptor

const file_api_base_setting_proto_rawDesc = "" +
	"\n" +
	"\x16api/base/setting.proto\x12\bapi.base\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x03\n" +
	"\aSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x1a\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x1a8\n" +
	"\vGetResponse\x12)\n" +
	"\x06result\x18\x01 \x01(\v2\x11.api.base.SettingR\x06result\x1a7\n" +
	"\rUpdateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x1a;\n" +
	"\x0eUpdateResponse\x12)\n" +
	"\x06result\x18\x01 \x01(\v2\x11.api.base.SettingR\x06result\x1a \n" +
	"\fResetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x1a\x0f\n" +
	"\rResetResponse2\xd3\x02\n" +
	"\x0eSettingService\x12l\n" +
	"\fResetSetting\x12\x1e.api.base.Setting.ResetRequest\x1a\x1f.api.base.Setting.ResetResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\"\x13/api/settings/reset\x12l\n" +
	"\rUpdateSetting\x12\x1f.api.base.Setting.UpdateRequest\x1a .api.base.Setting.UpdateResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/settings\x12e\n" +
	"\n" +
	"GetSetting\x12\x1c.api.base.Setting.GetRequest\x1a\x1d.api.base.Setting.GetResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/setting/{key}B\x9c\x01\n" +
	"\fcom.api.baseB\fSettingProtoP\x01Z=github.com/honmaple/maple-file/server/internal/proto/api/base\xa2\x02\x03ABX\xaa\x02\bApi.Base\xca\x02\bApi\\Base\xe2\x02\x14Api\\Base\\GPBMetadata\xea\x02\tApi::Baseb\x06proto3"

var (
	file_api_base_setting_proto_rawDescOnce sync.Once
	file_api_base_setting_proto_rawDescData []byte
)

func file_api_base_setting_proto_rawDescGZIP() []byte {
	file_api_base_setting_proto_rawDescOnce.Do(func() {
		file_api_base_setting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_base_setting_proto_rawDesc), len(file_api_base_setting_proto_rawDesc)))
	})
	return file_api_base_setting_proto_rawDescData
}

var file_api_base_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_base_setting_proto_goTypes = []any{
	(*Setting)(nil),                // 0: api.base.Setting
	(*Setting_GetRequest)(nil),     // 1: api.base.Setting.GetRequest
	(*Setting_GetResponse)(nil),    // 2: api.base.Setting.GetResponse
	(*Setting_UpdateRequest)(nil),  // 3: api.base.Setting.UpdateRequest
	(*Setting_UpdateResponse)(nil), // 4: api.base.Setting.UpdateResponse
	(*Setting_ResetRequest)(nil),   // 5: api.base.Setting.ResetRequest
	(*Setting_ResetResponse)(nil),  // 6: api.base.Setting.ResetResponse
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_api_base_setting_proto_depIdxs = []int32{
	7, // 0: api.base.Setting.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: api.base.Setting.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: api.base.Setting.GetResponse.result:type_name -> api.base.Setting
	0, // 3: api.base.Setting.UpdateResponse.result:type_name -> api.base.Setting
	5, // 4: api.base.SettingService.ResetSetting:input_type -> api.base.Setting.ResetRequest
	3, // 5: api.base.SettingService.UpdateSetting:input_type -> api.base.Setting.UpdateRequest
	1, // 6: api.base.SettingService.GetSetting:input_type -> api.base.Setting.GetRequest
	6, // 7: api.base.SettingService.ResetSetting:output_type -> api.base.Setting.ResetResponse
	4, // 8: api.base.SettingService.UpdateSetting:output_type -> api.base.Setting.UpdateResponse
	2, // 9: api.base.SettingService.GetSetting:output_type -> api.base.Setting.GetResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_base_setting_proto_init() }
func file_api_base_setting_proto_init() {
	if File_api_base_setting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_base_setting_proto_rawDesc), len(file_api_base_setting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_base_setting_proto_goTypes,
		DependencyIndexes: file_api_base_setting_proto_depIdxs,
		MessageInfos:      file_api_base_setting_proto_msgTypes,
	}.Build()
	File_api_base_setting_proto = out.File
	file_api_base_setting_proto_goTypes = nil
	file_api_base_setting_proto_depIdxs = nil
}
