// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/base/setting.proto

package base

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettingService_ResetSetting_FullMethodName  = "/api.base.SettingService/ResetSetting"
	SettingService_UpdateSetting_FullMethodName = "/api.base.SettingService/UpdateSetting"
	SettingService_GetSetting_FullMethodName    = "/api.base.SettingService/GetSetting"
)

// SettingServiceClient is the client API for SettingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettingServiceClient interface {
	ResetSetting(ctx context.Context, in *Setting_ResetRequest, opts ...grpc.CallOption) (*Setting_ResetResponse, error)
	UpdateSetting(ctx context.Context, in *Setting_UpdateRequest, opts ...grpc.CallOption) (*Setting_UpdateResponse, error)
	GetSetting(ctx context.Context, in *Setting_GetRequest, opts ...grpc.CallOption) (*Setting_GetResponse, error)
}

type settingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingServiceClient(cc grpc.ClientConnInterface) SettingServiceClient {
	return &settingServiceClient{cc}
}

func (c *settingServiceClient) ResetSetting(ctx context.Context, in *Setting_ResetRequest, opts ...grpc.CallOption) (*Setting_ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Setting_ResetResponse)
	err := c.cc.Invoke(ctx, SettingService_ResetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) UpdateSetting(ctx context.Context, in *Setting_UpdateRequest, opts ...grpc.CallOption) (*Setting_UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Setting_UpdateResponse)
	err := c.cc.Invoke(ctx, SettingService_UpdateSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) GetSetting(ctx context.Context, in *Setting_GetRequest, opts ...grpc.CallOption) (*Setting_GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Setting_GetResponse)
	err := c.cc.Invoke(ctx, SettingService_GetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingServiceServer is the server API for SettingService service.
// All implementations must embed UnimplementedSettingServiceServer
// for forward compatibility.
type SettingServiceServer interface {
	ResetSetting(context.Context, *Setting_ResetRequest) (*Setting_ResetResponse, error)
	UpdateSetting(context.Context, *Setting_UpdateRequest) (*Setting_UpdateResponse, error)
	GetSetting(context.Context, *Setting_GetRequest) (*Setting_GetResponse, error)
	mustEmbedUnimplementedSettingServiceServer()
}

// UnimplementedSettingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingServiceServer struct{}

func (UnimplementedSettingServiceServer) ResetSetting(context.Context, *Setting_ResetRequest) (*Setting_ResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetSetting not implemented")
}
func (UnimplementedSettingServiceServer) UpdateSetting(context.Context, *Setting_UpdateRequest) (*Setting_UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSetting not implemented")
}
func (UnimplementedSettingServiceServer) GetSetting(context.Context, *Setting_GetRequest) (*Setting_GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSetting not implemented")
}
func (UnimplementedSettingServiceServer) mustEmbedUnimplementedSettingServiceServer() {}
func (UnimplementedSettingServiceServer) testEmbeddedByValue()                        {}

// UnsafeSettingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingServiceServer will
// result in compilation errors.
type UnsafeSettingServiceServer interface {
	mustEmbedUnimplementedSettingServiceServer()
}

func RegisterSettingServiceServer(s grpc.ServiceRegistrar, srv SettingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSettingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingService_ServiceDesc, srv)
}

func _SettingService_ResetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Setting_ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).ResetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_ResetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).ResetSetting(ctx, req.(*Setting_ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_UpdateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Setting_UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).UpdateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_UpdateSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).UpdateSetting(ctx, req.(*Setting_UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_GetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Setting_GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).GetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_GetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).GetSetting(ctx, req.(*Setting_GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingService_ServiceDesc is the grpc.ServiceDesc for SettingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.base.SettingService",
	HandlerType: (*SettingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResetSetting",
			Handler:    _SettingService_ResetSetting_Handler,
		},
		{
			MethodName: "UpdateSetting",
			Handler:    _SettingService_UpdateSetting_Handler,
		},
		{
			MethodName: "GetSetting",
			Handler:    _SettingService_GetSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/base/setting.proto",
}
