// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/base/system.proto

package base

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Runtime       string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_api_base_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Info) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Info) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Info) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Info) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Info_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info_Request) Reset() {
	*x = Info_Request{}
	mi := &file_api_base_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info_Request) ProtoMessage() {}

func (x *Info_Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info_Request.ProtoReflect.Descriptor instead.
func (*Info_Request) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{0, 0}
}

type Info_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Info                  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info_Response) Reset() {
	*x = Info_Response{}
	mi := &file_api_base_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info_Response) ProtoMessage() {}

func (x *Info_Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info_Response.ProtoReflect.Descriptor instead.
func (*Info_Response) Descriptor() ([]byte, []int) {
	return file_api_base_system_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Info_Response) GetResult() *Info {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_api_base_system_proto protoreflect.FileDescriptor

const file_api_base_system_proto_rawDesc = "" +
	"\n" +
	"\x15api/base/system.proto\x12\bapi.base\x1a\x1cgoogle/api/annotations.proto\"\xbf\x01\n" +
	"\x04Info\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x1a\t\n" +
	"\aRequest\x1a2\n" +
	"\bResponse\x12&\n" +
	"\x06result\x18\x01 \x01(\v2\x0e.api.base.InfoR\x06result2[\n" +
	"\rSystemService\x12J\n" +
	"\x04Info\x12\x16.api.base.Info.Request\x1a\x17.api.base.Info.Response\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/api/infoB\x9b\x01\n" +
	"\fcom.api.baseB\vSystemProtoP\x01Z=github.com/honmaple/maple-file/server/internal/proto/api/base\xa2\x02\x03ABX\xaa\x02\bApi.Base\xca\x02\bApi\\Base\xe2\x02\x14Api\\Base\\GPBMetadata\xea\x02\tApi::Baseb\x06proto3"

var (
	file_api_base_system_proto_rawDescOnce sync.Once
	file_api_base_system_proto_rawDescData []byte
)

func file_api_base_system_proto_rawDescGZIP() []byte {
	file_api_base_system_proto_rawDescOnce.Do(func() {
		file_api_base_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_base_system_proto_rawDesc), len(file_api_base_system_proto_rawDesc)))
	})
	return file_api_base_system_proto_rawDescData
}

var file_api_base_system_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_base_system_proto_goTypes = []any{
	(*Info)(nil),          // 0: api.base.Info
	(*Info_Request)(nil),  // 1: api.base.Info.Request
	(*Info_Response)(nil), // 2: api.base.Info.Response
}
var file_api_base_system_proto_depIdxs = []int32{
	0, // 0: api.base.Info.Response.result:type_name -> api.base.Info
	1, // 1: api.base.SystemService.Info:input_type -> api.base.Info.Request
	2, // 2: api.base.SystemService.Info:output_type -> api.base.Info.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_base_system_proto_init() }
func file_api_base_system_proto_init() {
	if File_api_base_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_base_system_proto_rawDesc), len(file_api_base_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_base_system_proto_goTypes,
		DependencyIndexes: file_api_base_system_proto_depIdxs,
		MessageInfos:      file_api_base_system_proto_msgTypes,
	}.Build()
	File_api_base_system_proto = out.File
	file_api_base_system_proto_goTypes = nil
	file_api_base_system_proto_depIdxs = nil
}
