// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/base/task.proto

package base

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 0
	TaskState_TASK_STATE_RUNNING     TaskState = 1
	TaskState_TASK_STATE_SUCCEEDED   TaskState = 2
	TaskState_TASK_STATE_CANCELING   TaskState = 3
	TaskState_TASK_STATE_CANCELED    TaskState = 4
	TaskState_TASK_STATE_FAILED      TaskState = 5
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		// Duplicate value: 0: "TASK_STATE_PENDING",
		1: "TASK_STATE_RUNNING",
		2: "TASK_STATE_SUCCEEDED",
		3: "TASK_STATE_CANCELING",
		4: "TASK_STATE_CANCELED",
		5: "TASK_STATE_FAILED",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     0,
		"TASK_STATE_RUNNING":     1,
		"TASK_STATE_SUCCEEDED":   2,
		"TASK_STATE_CANCELING":   3,
		"TASK_STATE_CANCELED":    4,
		"TASK_STATE_FAILED":      5,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_base_task_proto_enumTypes[0].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_api_base_task_proto_enumTypes[0]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: gorm:"not null;unique"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" gorm:"not null;unique"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	EndTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"not null;"
	Name          string    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" gorm:"not null;"`
	State         TaskState `protobuf:"varint,5,opt,name=state,proto3,enum=api.base.TaskState" json:"state,omitempty"`
	Progress      float64   `protobuf:"fixed64,6,opt,name=progress,proto3" json:"progress,omitempty"`
	ProgressState string    `protobuf:"bytes,7,opt,name=progress_state,json=progressState,proto3" json:"progress_state,omitempty"`
	Log           string    `protobuf:"bytes,8,opt,name=log,proto3" json:"log,omitempty"`
	Err           string    `protobuf:"bytes,9,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_base_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Task) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *Task) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Task) GetProgressState() string {
	if x != nil {
		return x.ProgressState
	}
	return ""
}

func (x *Task) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *Task) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type PersistTask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: gorm:"primary_key;auto_increment"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key;auto_increment"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"serializer:protobuf_timestamp;type:datetime"`
	// @gotags: gorm:"not null;unique"
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" gorm:"not null;unique"`
	Status        bool   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Type          string `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Option        string `protobuf:"bytes,7,opt,name=option,proto3" json:"option,omitempty"`
	CronOption    string `protobuf:"bytes,8,opt,name=cron_option,json=cronOption,proto3" json:"cron_option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask) Reset() {
	*x = PersistTask{}
	mi := &file_api_base_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask) ProtoMessage() {}

func (x *PersistTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask.ProtoReflect.Descriptor instead.
func (*PersistTask) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1}
}

func (x *PersistTask) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersistTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PersistTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PersistTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersistTask) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *PersistTask) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PersistTask) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *PersistTask) GetCronOption() string {
	if x != nil {
		return x.CronOption
	}
	return ""
}

type Task_ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        map[string]string      `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_ListRequest) Reset() {
	*x = Task_ListRequest{}
	mi := &file_api_base_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_ListRequest) ProtoMessage() {}

func (x *Task_ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_ListRequest.ProtoReflect.Descriptor instead.
func (*Task_ListRequest) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Task_ListRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Task_ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Task                `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_ListResponse) Reset() {
	*x = Task_ListResponse{}
	mi := &file_api_base_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_ListResponse) ProtoMessage() {}

func (x *Task_ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_ListResponse.ProtoReflect.Descriptor instead.
func (*Task_ListResponse) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Task_ListResponse) GetResults() []*Task {
	if x != nil {
		return x.Results
	}
	return nil
}

type Task_RetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []string               `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_RetryRequest) Reset() {
	*x = Task_RetryRequest{}
	mi := &file_api_base_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_RetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_RetryRequest) ProtoMessage() {}

func (x *Task_RetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_RetryRequest.ProtoReflect.Descriptor instead.
func (*Task_RetryRequest) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Task_RetryRequest) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Task_RetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_RetryResponse) Reset() {
	*x = Task_RetryResponse{}
	mi := &file_api_base_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_RetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_RetryResponse) ProtoMessage() {}

func (x *Task_RetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_RetryResponse.ProtoReflect.Descriptor instead.
func (*Task_RetryResponse) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{0, 3}
}

type Task_CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []string               `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_CancelRequest) Reset() {
	*x = Task_CancelRequest{}
	mi := &file_api_base_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_CancelRequest) ProtoMessage() {}

func (x *Task_CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_CancelRequest.ProtoReflect.Descriptor instead.
func (*Task_CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Task_CancelRequest) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Task_CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_CancelResponse) Reset() {
	*x = Task_CancelResponse{}
	mi := &file_api_base_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_CancelResponse) ProtoMessage() {}

func (x *Task_CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_CancelResponse.ProtoReflect.Descriptor instead.
func (*Task_CancelResponse) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{0, 5}
}

type Task_RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []string               `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_RemoveRequest) Reset() {
	*x = Task_RemoveRequest{}
	mi := &file_api_base_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_RemoveRequest) ProtoMessage() {}

func (x *Task_RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_RemoveRequest.ProtoReflect.Descriptor instead.
func (*Task_RemoveRequest) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Task_RemoveRequest) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Task_RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task_RemoveResponse) Reset() {
	*x = Task_RemoveResponse{}
	mi := &file_api_base_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task_RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task_RemoveResponse) ProtoMessage() {}

func (x *Task_RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task_RemoveResponse.ProtoReflect.Descriptor instead.
func (*Task_RemoveResponse) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{0, 7}
}

type PersistTask_ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        map[string]string      `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_ListRequest) Reset() {
	*x = PersistTask_ListRequest{}
	mi := &file_api_base_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_ListRequest) ProtoMessage() {}

func (x *PersistTask_ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_ListRequest.ProtoReflect.Descriptor instead.
func (*PersistTask_ListRequest) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 0}
}

func (x *PersistTask_ListRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type PersistTask_ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PersistTask         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_ListResponse) Reset() {
	*x = PersistTask_ListResponse{}
	mi := &file_api_base_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_ListResponse) ProtoMessage() {}

func (x *PersistTask_ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_ListResponse.ProtoReflect.Descriptor instead.
func (*PersistTask_ListResponse) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 1}
}

func (x *PersistTask_ListResponse) GetResults() []*PersistTask {
	if x != nil {
		return x.Results
	}
	return nil
}

type PersistTask_CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *PersistTask           `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_CreateRequest) Reset() {
	*x = PersistTask_CreateRequest{}
	mi := &file_api_base_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_CreateRequest) ProtoMessage() {}

func (x *PersistTask_CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_CreateRequest.ProtoReflect.Descriptor instead.
func (*PersistTask_CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 2}
}

func (x *PersistTask_CreateRequest) GetPayload() *PersistTask {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PersistTask_CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *PersistTask           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_CreateResponse) Reset() {
	*x = PersistTask_CreateResponse{}
	mi := &file_api_base_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_CreateResponse) ProtoMessage() {}

func (x *PersistTask_CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_CreateResponse.ProtoReflect.Descriptor instead.
func (*PersistTask_CreateResponse) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 3}
}

func (x *PersistTask_CreateResponse) GetResult() *PersistTask {
	if x != nil {
		return x.Result
	}
	return nil
}

type PersistTask_UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *PersistTask           `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_UpdateRequest) Reset() {
	*x = PersistTask_UpdateRequest{}
	mi := &file_api_base_task_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_UpdateRequest) ProtoMessage() {}

func (x *PersistTask_UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_UpdateRequest.ProtoReflect.Descriptor instead.
func (*PersistTask_UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 4}
}

func (x *PersistTask_UpdateRequest) GetPayload() *PersistTask {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PersistTask_UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *PersistTask           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_UpdateResponse) Reset() {
	*x = PersistTask_UpdateResponse{}
	mi := &file_api_base_task_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_UpdateResponse) ProtoMessage() {}

func (x *PersistTask_UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_UpdateResponse.ProtoReflect.Descriptor instead.
func (*PersistTask_UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 5}
}

func (x *PersistTask_UpdateResponse) GetResult() *PersistTask {
	if x != nil {
		return x.Result
	}
	return nil
}

type PersistTask_DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_DeleteRequest) Reset() {
	*x = PersistTask_DeleteRequest{}
	mi := &file_api_base_task_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_DeleteRequest) ProtoMessage() {}

func (x *PersistTask_DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_DeleteRequest.ProtoReflect.Descriptor instead.
func (*PersistTask_DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 6}
}

func (x *PersistTask_DeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PersistTask_DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_DeleteResponse) Reset() {
	*x = PersistTask_DeleteResponse{}
	mi := &file_api_base_task_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_DeleteResponse) ProtoMessage() {}

func (x *PersistTask_DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_DeleteResponse.ProtoReflect.Descriptor instead.
func (*PersistTask_DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 7}
}

type PersistTask_TestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *PersistTask           `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_TestRequest) Reset() {
	*x = PersistTask_TestRequest{}
	mi := &file_api_base_task_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_TestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_TestRequest) ProtoMessage() {}

func (x *PersistTask_TestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_TestRequest.ProtoReflect.Descriptor instead.
func (*PersistTask_TestRequest) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 8}
}

func (x *PersistTask_TestRequest) GetPayload() *PersistTask {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PersistTask_TestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_TestResponse) Reset() {
	*x = PersistTask_TestResponse{}
	mi := &file_api_base_task_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_TestResponse) ProtoMessage() {}

func (x *PersistTask_TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_TestResponse.ProtoReflect.Descriptor instead.
func (*PersistTask_TestResponse) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 9}
}

type PersistTask_ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DryRun        bool                   `protobuf:"varint,2,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_ExecuteRequest) Reset() {
	*x = PersistTask_ExecuteRequest{}
	mi := &file_api_base_task_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_ExecuteRequest) ProtoMessage() {}

func (x *PersistTask_ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_ExecuteRequest.ProtoReflect.Descriptor instead.
func (*PersistTask_ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 10}
}

func (x *PersistTask_ExecuteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersistTask_ExecuteRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type PersistTask_ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistTask_ExecuteResponse) Reset() {
	*x = PersistTask_ExecuteResponse{}
	mi := &file_api_base_task_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistTask_ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistTask_ExecuteResponse) ProtoMessage() {}

func (x *PersistTask_ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_base_task_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistTask_ExecuteResponse.ProtoReflect.Descriptor instead.
func (*PersistTask_ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_base_task_proto_rawDescGZIP(), []int{1, 11}
}

var File_api_base_task_proto protoreflect.FileDescriptor

const file_api_base_task_proto_rawDesc = "" +
	"\n" +
	"\x13api/base/task.proto\x12\bapi.base\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x05\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12)\n" +
	"\x05state\x18\x05 \x01(\x0e2\x13.api.base.TaskStateR\x05state\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x01R\bprogress\x12%\n" +
	"\x0eprogress_state\x18\a \x01(\tR\rprogressState\x12\x10\n" +
	"\x03log\x18\b \x01(\tR\x03log\x12\x10\n" +
	"\x03err\x18\t \x01(\tR\x03err\x1a\x88\x01\n" +
	"\vListRequest\x12>\n" +
	"\x06filter\x18\x01 \x03(\v2&.api.base.Task.ListRequest.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a8\n" +
	"\fListResponse\x12(\n" +
	"\aresults\x18\x01 \x03(\v2\x0e.api.base.TaskR\aresults\x1a$\n" +
	"\fRetryRequest\x12\x14\n" +
	"\x05tasks\x18\x01 \x03(\tR\x05tasks\x1a\x0f\n" +
	"\rRetryResponse\x1a%\n" +
	"\rCancelRequest\x12\x14\n" +
	"\x05tasks\x18\x01 \x03(\tR\x05tasks\x1a\x10\n" +
	"\x0eCancelResponse\x1a%\n" +
	"\rRemoveRequest\x12\x14\n" +
	"\x05tasks\x18\x01 \x03(\tR\x05tasks\x1a\x10\n" +
	"\x0eRemoveResponse\"\xb6\a\n" +
	"\vPersistTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x16\n" +
	"\x06option\x18\a \x01(\tR\x06option\x12\x1f\n" +
	"\vcron_option\x18\b \x01(\tR\n" +
	"cronOption\x1a\x8f\x01\n" +
	"\vListRequest\x12E\n" +
	"\x06filter\x18\x01 \x03(\v2-.api.base.PersistTask.ListRequest.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\fListResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.api.base.PersistTaskR\aresults\x1a@\n" +
	"\rCreateRequest\x12/\n" +
	"\apayload\x18\x01 \x01(\v2\x15.api.base.PersistTaskR\apayload\x1a?\n" +
	"\x0eCreateResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.api.base.PersistTaskR\x06result\x1a@\n" +
	"\rUpdateRequest\x12/\n" +
	"\apayload\x18\x01 \x01(\v2\x15.api.base.PersistTaskR\apayload\x1a?\n" +
	"\x0eUpdateResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.api.base.PersistTaskR\x06result\x1a\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x1a\x10\n" +
	"\x0eDeleteResponse\x1a>\n" +
	"\vTestRequest\x12/\n" +
	"\apayload\x18\x01 \x01(\v2\x15.api.base.PersistTaskR\apayload\x1a\x0e\n" +
	"\fTestResponse\x1a9\n" +
	"\x0eExecuteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\adry_run\x18\x02 \x01(\bR\x06dryRun\x1a\x11\n" +
	"\x0fExecuteResponse*\xbf\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x01\x12\x18\n" +
	"\x14TASK_STATE_SUCCEEDED\x10\x02\x12\x18\n" +
	"\x14TASK_STATE_CANCELING\x10\x03\x12\x17\n" +
	"\x13TASK_STATE_CANCELED\x10\x04\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x05\x1a\x02\x10\x012\xee\b\n" +
	"\vTaskService\x12_\n" +
	"\tListTasks\x12\x1a.api.base.Task.ListRequest\x1a\x1b.api.base.Task.ListResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/task/list\x12b\n" +
	"\tRetryTask\x12\x1b.api.base.Task.RetryRequest\x1a\x1c.api.base.Task.RetryResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/task/retry\x12f\n" +
	"\n" +
	"CancelTask\x12\x1c.api.base.Task.CancelRequest\x1a\x1d.api.base.Task.CancelResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/task/cancel\x12f\n" +
	"\n" +
	"RemoveTask\x12\x1c.api.base.Task.RemoveRequest\x1a\x1d.api.base.Task.RemoveResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/task/remove\x12y\n" +
	"\x10ListPersistTasks\x12!.api.base.PersistTask.ListRequest\x1a\".api.base.PersistTask.ListResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/task/persist/list\x12|\n" +
	"\x11CreatePersistTask\x12#.api.base.PersistTask.CreateRequest\x1a$.api.base.PersistTask.CreateResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/task/persist\x12\x8f\x01\n" +
	"\x11UpdatePersistTask\x12#.api.base.PersistTask.UpdateRequest\x1a$.api.base.PersistTask.UpdateResponse\"/\x82\xd3\xe4\x93\x02):\apayload\x1a\x1e/api/task/persist/{payload.id}\x12~\n" +
	"\x11DeletePersistTask\x12#.api.base.PersistTask.DeleteRequest\x1a$.api.base.PersistTask.DeleteResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/api/task/persist/{id}\x12Z\n" +
	"\x0fTestPersistTask\x12!.api.base.PersistTask.TestRequest\x1a\".api.base.PersistTask.TestResponse\"\x00\x12c\n" +
	"\x12ExecutePersistTask\x12$.api.base.PersistTask.ExecuteRequest\x1a%.api.base.PersistTask.ExecuteResponse\"\x00B\x99\x01\n" +
	"\fcom.api.baseB\tTaskProtoP\x01Z=github.com/honmaple/maple-file/server/internal/proto/api/base\xa2\x02\x03ABX\xaa\x02\bApi.Base\xca\x02\bApi\\Base\xe2\x02\x14Api\\Base\\GPBMetadata\xea\x02\tApi::Baseb\x06proto3"

var (
	file_api_base_task_proto_rawDescOnce sync.Once
	file_api_base_task_proto_rawDescData []byte
)

func file_api_base_task_proto_rawDescGZIP() []byte {
	file_api_base_task_proto_rawDescOnce.Do(func() {
		file_api_base_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_base_task_proto_rawDesc), len(file_api_base_task_proto_rawDesc)))
	})
	return file_api_base_task_proto_rawDescData
}

var file_api_base_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_base_task_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_base_task_proto_goTypes = []any{
	(TaskState)(0),                      // 0: api.base.TaskState
	(*Task)(nil),                        // 1: api.base.Task
	(*PersistTask)(nil),                 // 2: api.base.PersistTask
	(*Task_ListRequest)(nil),            // 3: api.base.Task.ListRequest
	(*Task_ListResponse)(nil),           // 4: api.base.Task.ListResponse
	(*Task_RetryRequest)(nil),           // 5: api.base.Task.RetryRequest
	(*Task_RetryResponse)(nil),          // 6: api.base.Task.RetryResponse
	(*Task_CancelRequest)(nil),          // 7: api.base.Task.CancelRequest
	(*Task_CancelResponse)(nil),         // 8: api.base.Task.CancelResponse
	(*Task_RemoveRequest)(nil),          // 9: api.base.Task.RemoveRequest
	(*Task_RemoveResponse)(nil),         // 10: api.base.Task.RemoveResponse
	nil,                                 // 11: api.base.Task.ListRequest.FilterEntry
	(*PersistTask_ListRequest)(nil),     // 12: api.base.PersistTask.ListRequest
	(*PersistTask_ListResponse)(nil),    // 13: api.base.PersistTask.ListResponse
	(*PersistTask_CreateRequest)(nil),   // 14: api.base.PersistTask.CreateRequest
	(*PersistTask_CreateResponse)(nil),  // 15: api.base.PersistTask.CreateResponse
	(*PersistTask_UpdateRequest)(nil),   // 16: api.base.PersistTask.UpdateRequest
	(*PersistTask_UpdateResponse)(nil),  // 17: api.base.PersistTask.UpdateResponse
	(*PersistTask_DeleteRequest)(nil),   // 18: api.base.PersistTask.DeleteRequest
	(*PersistTask_DeleteResponse)(nil),  // 19: api.base.PersistTask.DeleteResponse
	(*PersistTask_TestRequest)(nil),     // 20: api.base.PersistTask.TestRequest
	(*PersistTask_TestResponse)(nil),    // 21: api.base.PersistTask.TestResponse
	(*PersistTask_ExecuteRequest)(nil),  // 22: api.base.PersistTask.ExecuteRequest
	(*PersistTask_ExecuteResponse)(nil), // 23: api.base.PersistTask.ExecuteResponse
	nil,                                 // 24: api.base.PersistTask.ListRequest.FilterEntry
	(*timestamppb.Timestamp)(nil),       // 25: google.protobuf.Timestamp
}
var file_api_base_task_proto_depIdxs = []int32{
	25, // 0: api.base.Task.start_time:type_name -> google.protobuf.Timestamp
	25, // 1: api.base.Task.end_time:type_name -> google.protobuf.Timestamp
	0,  // 2: api.base.Task.state:type_name -> api.base.TaskState
	25, // 3: api.base.PersistTask.created_at:type_name -> google.protobuf.Timestamp
	25, // 4: api.base.PersistTask.updated_at:type_name -> google.protobuf.Timestamp
	11, // 5: api.base.Task.ListRequest.filter:type_name -> api.base.Task.ListRequest.FilterEntry
	1,  // 6: api.base.Task.ListResponse.results:type_name -> api.base.Task
	24, // 7: api.base.PersistTask.ListRequest.filter:type_name -> api.base.PersistTask.ListRequest.FilterEntry
	2,  // 8: api.base.PersistTask.ListResponse.results:type_name -> api.base.PersistTask
	2,  // 9: api.base.PersistTask.CreateRequest.payload:type_name -> api.base.PersistTask
	2,  // 10: api.base.PersistTask.CreateResponse.result:type_name -> api.base.PersistTask
	2,  // 11: api.base.PersistTask.UpdateRequest.payload:type_name -> api.base.PersistTask
	2,  // 12: api.base.PersistTask.UpdateResponse.result:type_name -> api.base.PersistTask
	2,  // 13: api.base.PersistTask.TestRequest.payload:type_name -> api.base.PersistTask
	3,  // 14: api.base.TaskService.ListTasks:input_type -> api.base.Task.ListRequest
	5,  // 15: api.base.TaskService.RetryTask:input_type -> api.base.Task.RetryRequest
	7,  // 16: api.base.TaskService.CancelTask:input_type -> api.base.Task.CancelRequest
	9,  // 17: api.base.TaskService.RemoveTask:input_type -> api.base.Task.RemoveRequest
	12, // 18: api.base.TaskService.ListPersistTasks:input_type -> api.base.PersistTask.ListRequest
	14, // 19: api.base.TaskService.CreatePersistTask:input_type -> api.base.PersistTask.CreateRequest
	16, // 20: api.base.TaskService.UpdatePersistTask:input_type -> api.base.PersistTask.UpdateRequest
	18, // 21: api.base.TaskService.DeletePersistTask:input_type -> api.base.PersistTask.DeleteRequest
	20, // 22: api.base.TaskService.TestPersistTask:input_type -> api.base.PersistTask.TestRequest
	22, // 23: api.base.TaskService.ExecutePersistTask:input_type -> api.base.PersistTask.ExecuteRequest
	4,  // 24: api.base.TaskService.ListTasks:output_type -> api.base.Task.ListResponse
	6,  // 25: api.base.TaskService.RetryTask:output_type -> api.base.Task.RetryResponse
	8,  // 26: api.base.TaskService.CancelTask:output_type -> api.base.Task.CancelResponse
	10, // 27: api.base.TaskService.RemoveTask:output_type -> api.base.Task.RemoveResponse
	13, // 28: api.base.TaskService.ListPersistTasks:output_type -> api.base.PersistTask.ListResponse
	15, // 29: api.base.TaskService.CreatePersistTask:output_type -> api.base.PersistTask.CreateResponse
	17, // 30: api.base.TaskService.UpdatePersistTask:output_type -> api.base.PersistTask.UpdateResponse
	19, // 31: api.base.TaskService.DeletePersistTask:output_type -> api.base.PersistTask.DeleteResponse
	21, // 32: api.base.TaskService.TestPersistTask:output_type -> api.base.PersistTask.TestResponse
	23, // 33: api.base.TaskService.ExecutePersistTask:output_type -> api.base.PersistTask.ExecuteResponse
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_base_task_proto_init() }
func file_api_base_task_proto_init() {
	if File_api_base_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_base_task_proto_rawDesc), len(file_api_base_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_base_task_proto_goTypes,
		DependencyIndexes: file_api_base_task_proto_depIdxs,
		EnumInfos:         file_api_base_task_proto_enumTypes,
		MessageInfos:      file_api_base_task_proto_msgTypes,
	}.Build()
	File_api_base_task_proto = out.File
	file_api_base_task_proto_goTypes = nil
	file_api_base_task_proto_depIdxs = nil
}
