// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/base/task.proto

package base

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_ListTasks_FullMethodName          = "/api.base.TaskService/ListTasks"
	TaskService_RetryTask_FullMethodName          = "/api.base.TaskService/RetryTask"
	TaskService_CancelTask_FullMethodName         = "/api.base.TaskService/CancelTask"
	TaskService_RemoveTask_FullMethodName         = "/api.base.TaskService/RemoveTask"
	TaskService_ListPersistTasks_FullMethodName   = "/api.base.TaskService/ListPersistTasks"
	TaskService_CreatePersistTask_FullMethodName  = "/api.base.TaskService/CreatePersistTask"
	TaskService_UpdatePersistTask_FullMethodName  = "/api.base.TaskService/UpdatePersistTask"
	TaskService_DeletePersistTask_FullMethodName  = "/api.base.TaskService/DeletePersistTask"
	TaskService_TestPersistTask_FullMethodName    = "/api.base.TaskService/TestPersistTask"
	TaskService_ExecutePersistTask_FullMethodName = "/api.base.TaskService/ExecutePersistTask"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	ListTasks(ctx context.Context, in *Task_ListRequest, opts ...grpc.CallOption) (*Task_ListResponse, error)
	RetryTask(ctx context.Context, in *Task_RetryRequest, opts ...grpc.CallOption) (*Task_RetryResponse, error)
	CancelTask(ctx context.Context, in *Task_CancelRequest, opts ...grpc.CallOption) (*Task_CancelResponse, error)
	RemoveTask(ctx context.Context, in *Task_RemoveRequest, opts ...grpc.CallOption) (*Task_RemoveResponse, error)
	ListPersistTasks(ctx context.Context, in *PersistTask_ListRequest, opts ...grpc.CallOption) (*PersistTask_ListResponse, error)
	CreatePersistTask(ctx context.Context, in *PersistTask_CreateRequest, opts ...grpc.CallOption) (*PersistTask_CreateResponse, error)
	UpdatePersistTask(ctx context.Context, in *PersistTask_UpdateRequest, opts ...grpc.CallOption) (*PersistTask_UpdateResponse, error)
	DeletePersistTask(ctx context.Context, in *PersistTask_DeleteRequest, opts ...grpc.CallOption) (*PersistTask_DeleteResponse, error)
	TestPersistTask(ctx context.Context, in *PersistTask_TestRequest, opts ...grpc.CallOption) (*PersistTask_TestResponse, error)
	ExecutePersistTask(ctx context.Context, in *PersistTask_ExecuteRequest, opts ...grpc.CallOption) (*PersistTask_ExecuteResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) ListTasks(ctx context.Context, in *Task_ListRequest, opts ...grpc.CallOption) (*Task_ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task_ListResponse)
	err := c.cc.Invoke(ctx, TaskService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RetryTask(ctx context.Context, in *Task_RetryRequest, opts ...grpc.CallOption) (*Task_RetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task_RetryResponse)
	err := c.cc.Invoke(ctx, TaskService_RetryTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CancelTask(ctx context.Context, in *Task_CancelRequest, opts ...grpc.CallOption) (*Task_CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task_CancelResponse)
	err := c.cc.Invoke(ctx, TaskService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RemoveTask(ctx context.Context, in *Task_RemoveRequest, opts ...grpc.CallOption) (*Task_RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task_RemoveResponse)
	err := c.cc.Invoke(ctx, TaskService_RemoveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListPersistTasks(ctx context.Context, in *PersistTask_ListRequest, opts ...grpc.CallOption) (*PersistTask_ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersistTask_ListResponse)
	err := c.cc.Invoke(ctx, TaskService_ListPersistTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) CreatePersistTask(ctx context.Context, in *PersistTask_CreateRequest, opts ...grpc.CallOption) (*PersistTask_CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersistTask_CreateResponse)
	err := c.cc.Invoke(ctx, TaskService_CreatePersistTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdatePersistTask(ctx context.Context, in *PersistTask_UpdateRequest, opts ...grpc.CallOption) (*PersistTask_UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersistTask_UpdateResponse)
	err := c.cc.Invoke(ctx, TaskService_UpdatePersistTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeletePersistTask(ctx context.Context, in *PersistTask_DeleteRequest, opts ...grpc.CallOption) (*PersistTask_DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersistTask_DeleteResponse)
	err := c.cc.Invoke(ctx, TaskService_DeletePersistTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TestPersistTask(ctx context.Context, in *PersistTask_TestRequest, opts ...grpc.CallOption) (*PersistTask_TestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersistTask_TestResponse)
	err := c.cc.Invoke(ctx, TaskService_TestPersistTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ExecutePersistTask(ctx context.Context, in *PersistTask_ExecuteRequest, opts ...grpc.CallOption) (*PersistTask_ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PersistTask_ExecuteResponse)
	err := c.cc.Invoke(ctx, TaskService_ExecutePersistTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
type TaskServiceServer interface {
	ListTasks(context.Context, *Task_ListRequest) (*Task_ListResponse, error)
	RetryTask(context.Context, *Task_RetryRequest) (*Task_RetryResponse, error)
	CancelTask(context.Context, *Task_CancelRequest) (*Task_CancelResponse, error)
	RemoveTask(context.Context, *Task_RemoveRequest) (*Task_RemoveResponse, error)
	ListPersistTasks(context.Context, *PersistTask_ListRequest) (*PersistTask_ListResponse, error)
	CreatePersistTask(context.Context, *PersistTask_CreateRequest) (*PersistTask_CreateResponse, error)
	UpdatePersistTask(context.Context, *PersistTask_UpdateRequest) (*PersistTask_UpdateResponse, error)
	DeletePersistTask(context.Context, *PersistTask_DeleteRequest) (*PersistTask_DeleteResponse, error)
	TestPersistTask(context.Context, *PersistTask_TestRequest) (*PersistTask_TestResponse, error)
	ExecutePersistTask(context.Context, *PersistTask_ExecuteRequest) (*PersistTask_ExecuteResponse, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) ListTasks(context.Context, *Task_ListRequest) (*Task_ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskServiceServer) RetryTask(context.Context, *Task_RetryRequest) (*Task_RetryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryTask not implemented")
}
func (UnimplementedTaskServiceServer) CancelTask(context.Context, *Task_CancelRequest) (*Task_CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedTaskServiceServer) RemoveTask(context.Context, *Task_RemoveRequest) (*Task_RemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTask not implemented")
}
func (UnimplementedTaskServiceServer) ListPersistTasks(context.Context, *PersistTask_ListRequest) (*PersistTask_ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPersistTasks not implemented")
}
func (UnimplementedTaskServiceServer) CreatePersistTask(context.Context, *PersistTask_CreateRequest) (*PersistTask_CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePersistTask not implemented")
}
func (UnimplementedTaskServiceServer) UpdatePersistTask(context.Context, *PersistTask_UpdateRequest) (*PersistTask_UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePersistTask not implemented")
}
func (UnimplementedTaskServiceServer) DeletePersistTask(context.Context, *PersistTask_DeleteRequest) (*PersistTask_DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePersistTask not implemented")
}
func (UnimplementedTaskServiceServer) TestPersistTask(context.Context, *PersistTask_TestRequest) (*PersistTask_TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestPersistTask not implemented")
}
func (UnimplementedTaskServiceServer) ExecutePersistTask(context.Context, *PersistTask_ExecuteRequest) (*PersistTask_ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutePersistTask not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call pancis, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task_ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTasks(ctx, req.(*Task_ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_RetryTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task_RetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).RetryTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_RetryTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RetryTask(ctx, req.(*Task_RetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task_CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CancelTask(ctx, req.(*Task_CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_RemoveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Task_RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).RemoveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_RemoveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RemoveTask(ctx, req.(*Task_RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListPersistTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistTask_ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListPersistTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListPersistTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListPersistTasks(ctx, req.(*PersistTask_ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_CreatePersistTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistTask_CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreatePersistTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreatePersistTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreatePersistTask(ctx, req.(*PersistTask_CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdatePersistTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistTask_UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdatePersistTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdatePersistTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdatePersistTask(ctx, req.(*PersistTask_UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeletePersistTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistTask_DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeletePersistTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_DeletePersistTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeletePersistTask(ctx, req.(*PersistTask_DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TestPersistTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistTask_TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TestPersistTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TestPersistTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TestPersistTask(ctx, req.(*PersistTask_TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ExecutePersistTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistTask_ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ExecutePersistTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ExecutePersistTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ExecutePersistTask(ctx, req.(*PersistTask_ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.base.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTasks",
			Handler:    _TaskService_ListTasks_Handler,
		},
		{
			MethodName: "RetryTask",
			Handler:    _TaskService_RetryTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _TaskService_CancelTask_Handler,
		},
		{
			MethodName: "RemoveTask",
			Handler:    _TaskService_RemoveTask_Handler,
		},
		{
			MethodName: "ListPersistTasks",
			Handler:    _TaskService_ListPersistTasks_Handler,
		},
		{
			MethodName: "CreatePersistTask",
			Handler:    _TaskService_CreatePersistTask_Handler,
		},
		{
			MethodName: "UpdatePersistTask",
			Handler:    _TaskService_UpdatePersistTask_Handler,
		},
		{
			MethodName: "DeletePersistTask",
			Handler:    _TaskService_DeletePersistTask_Handler,
		},
		{
			MethodName: "TestPersistTask",
			Handler:    _TaskService_TestPersistTask_Handler,
		},
		{
			MethodName: "ExecutePersistTask",
			Handler:    _TaskService_ExecutePersistTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/base/task.proto",
}
