syntax = "proto3";

package api.base;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "api/base";

service TaskService {
	rpc ListTasks (Task.ListRequest) returns (Task.ListResponse) {
		option (google.api.http) = {
			post: "/api/task/list"
			body: "*"
		};
	}
	rpc RetryTask (Task.RetryRequest) returns (Task.RetryResponse) {
		option (google.api.http) = {
			post: "/api/task/retry"
			body: "*"
		};
	}
	rpc CancelTask (Task.CancelRequest) returns (Task.CancelResponse) {
		option (google.api.http) = {
			post: "/api/task/cancel"
			body: "*"
		};
	}
	rpc RemoveTask (Task.RemoveRequest) returns (Task.RemoveResponse) {
		option (google.api.http) = {
			post: "/api/task/remove"
			body: "*"
		};
	}

	rpc ListPersistTasks (PersistTask.ListRequest) returns (PersistTask.ListResponse) {
		option (google.api.http) = {
			get: "/api/task/persist/list"
		};
	}
	rpc CreatePersistTask (PersistTask.CreateRequest) returns (PersistTask.CreateResponse) {
		option (google.api.http) = {
			post: "/api/task/persist"
			body: "*"
		};
	}
	rpc UpdatePersistTask (PersistTask.UpdateRequest) returns (PersistTask.UpdateResponse) {
		option (google.api.http) = {
			put: "/api/task/persist/{payload.id}"
			body: "payload"
		};
	}
	rpc DeletePersistTask (PersistTask.DeleteRequest) returns (PersistTask.DeleteResponse) {
		option (google.api.http) = {
			delete: "/api/task/persist/{id}"
		};
	}
	rpc TestPersistTask (PersistTask.TestRequest) returns (PersistTask.TestResponse) {}
	rpc ExecutePersistTask (PersistTask.ExecuteRequest) returns (PersistTask.ExecuteResponse) {}
}

enum TaskState {
	option allow_alias = true;
	TASK_STATE_UNSPECIFIED = 0;

	TASK_STATE_PENDING = 0;
	TASK_STATE_RUNNING = 1;
	TASK_STATE_SUCCEEDED = 2;
	TASK_STATE_CANCELING = 3;
	TASK_STATE_CANCELED = 4;
	TASK_STATE_FAILED = 5;
}

message Task {
	// @gotags: gorm:"not null;unique"
	string id = 1;
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	google.protobuf.Timestamp start_time = 2;
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	google.protobuf.Timestamp end_time   = 3;

	// @gotags: gorm:"not null;"
	string    name = 4;
	TaskState state = 5;
	double progress = 6;
	string progress_state = 7;
	string log = 8;
	string err = 9;

	message ListRequest {
		map<string, string> filter = 1;
	}

	message ListResponse {
		repeated Task results = 1;
	}

	message RetryRequest {
		repeated string tasks = 1;
	}

	message RetryResponse {
	}

	message CancelRequest {
		repeated string tasks = 1;
	}

	message CancelResponse {
	}

	message RemoveRequest {
		repeated string tasks = 1;
	}

	message RemoveResponse {
	}
}

message PersistTask {
	// @gotags: gorm:"primary_key;auto_increment"
	int32 id = 1;
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	google.protobuf.Timestamp created_at = 2;
	// @gotags: gorm:"serializer:protobuf_timestamp;type:datetime"
	google.protobuf.Timestamp updated_at = 3;

	// @gotags: gorm:"not null;unique"
	string name = 4;
	bool   status = 5;
	string type = 6;
	string option = 7;
	string cron_option = 8;

	message ListRequest {
		map<string, string> filter = 1;
	}

	message ListResponse {
		repeated PersistTask results = 1;
	}

	message CreateRequest {
		PersistTask payload = 1;
	}

	message CreateResponse {
		PersistTask result = 1;
	}

	message UpdateRequest {
		PersistTask payload = 1;
	}

	message UpdateResponse {
		PersistTask result = 1;
	}

	message DeleteRequest {
		int32 id = 1;
	}

	message DeleteResponse {
	}

	message TestRequest {
		PersistTask payload = 1;
	}

	message TestResponse {
	}

	message ExecuteRequest {
		int32 id = 1;
		bool dry_run = 2;
	}

	message ExecuteResponse {
	}
}
